spring:
  application:
    name: movie-reservation-service
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/movie_reservation
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  level:
    web: info
    sql: info
jwt:
  secret:
    key: my-hidden-secret-dythdmy-hidden-secret-dythdmy-hidden-secret-dythdmy-hidden-secret-dythd #Should be 256 characters
